# Generated by Django 2.2.5 on 2019-10-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatatdcu.Campus')),
            ],
        ),
    ]
