# Generated by Django 2.2.5 on 2019-10-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
