# Generated by Django 2.2.5 on 2019-10-29 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0002_restaurant_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='week_end_closing_hours',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='week_end_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='week_end_opening_hours',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
