# Generated by Django 2.2.5 on 2019-11-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0003_auto_20191029_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='description',
            field=models.CharField(default='This campus is associate to the whole DCU Campus', max_length=500),
        ),
    ]
